### ISSUE TITLE
Pin the `redis` version

### ISSUE THREAD

**Issue by mmalecki** [ddollar/redis-url#14]
Right now we specify `>= 0.0.1` as the `redis` version we depend on. This means that when running `npm install` the latest will always be pulled. This is unsafe in production, as `npm install` can bring down an incompatible version without a way for the user to stop this.

There's a way for users to walk this around, and that's specifying their own `redis` module version in their `package.json` and using `redisUrl.parse`, but I think it's worth addressing either way. I think the simplest way to do it would be to specify a minor version of `redis` that we depend on, and bump it together with our minor when a new version comes out. We could also probably maybe use peer dependencies, but those are bad and we shouldn't.  
Or, we should at least warn users that this is the case in our README.

**Comment by psirenny** [comment]
I was recently bit by this issue. I think #18 resolves this.
