### ISSUE TITLE
incorrect db-number description in README

### ISSUE THREAD

**Issue by cvrebert** [ddollar/redis-url#15]
From the README:
> **db-number** is an integer from 1 to 15

This is inaccurate. Redis database numbers start at 0 (see http://redis.io/commands/SELECT), and the total number of databases is controlled by the `databases` directive in [`redis.conf`](https://raw.githubusercontent.com/antirez/redis/2.8/redis.conf).

**Comment by zeke** [comment]
Thanks for pointing this out, @cvrebert. Patches welcome.
